### ISSUE TITLE
Shooter checklist

### ISSUE THREAD

**Issue by rakrakon** [Galaxia5987/robot-2024#33]
# Shooter checklist
## Calibration
- [x] Feedforward has been calibrated (SysID)
- [x] PID has been calibrated
## Motor configs
- [x] Top motor gets correct constants in configurator 
- [x] Bottom motor gets correct constants configurator
### Top Roller
- [x] VelocitySetpoint is updating & logical value
- [x] Velocity is updating & logical value
- [x] Voltage is updating & logical value
### Bottom Roller
- [x] VelocitySetpoint is updating & logical value
- [x] Velocity is updating & logical value
- [x] Voltage is updating & logical value
## Constants
- [x] set point tolerance top has been calibrated
- [x] set point tolerance bottom has been calibrated
- [x] Shooter height has been calibrated
- [x] Top inversion has been calibrated
- [x] Bottom inversion has been calibrated
- [x] Velocity by distance map has been calibrated
## Subsystem functions
- [x] SetTopVelocity sets the motor to the correct velocity
- [x] SetBottomVelocity sets the motor to the correct velocity
- [x] Stop function stops the both motors
- [x] AtSetpoint works as expected
## Subsystem commands
- [x] SetVelocity  command with different roller speeds works as expected
- [x] SetVelocity  command with identical roller speeds works as expected
- [x] Stop command stops the subsystem
