### ISSUE TITLE
Hood checklist

### ISSUE THREAD

**Issue by rakrakon** [Galaxia5987/robot-2024#34]
# Hood checklist
## Calibration
- [x] PID has been calibrated
- [x] Feedforward has been calibrated (SysID)
## Motor configs
- [x] Motor gets correct constants in configurator 
## Logger Inputs
- [x] AngleSetpoint is updating & logical value
- [x] Angle is updating & logical value
- [x] AbsoluteAngle is updating & logical value
- [x] PowerSetpoint is updating & logical value
- [x] Voltage is updating & logical value
- [x] ControlMode 
# Constants
- [x] Position tolerance has been calibrated
- [x] Inversion has been calibrated
- [x] Absolute encoder offset has been calibrated
## Subsystem functions
- [x] SetAngle sets the motor to the correct angle
- [x] SetPower sets the motor to the correct power
- [x] UpdateInternalEncoder updates the internal encoder & logical value
- [x] AtSetpoint works as expected
## Subsystem commands
- [x] SetAngle command works as expected
- [x] SetPower command works as expected
- [x] UpdateInternalEncoder command works as expected
