### ISSUE TITLE
Intake checklist

### ISSUE THREAD

**Issue by rakrakon** [Galaxia5987/robot-2024#40]
# Intake checklist
## Calibration
- [x] Angle PID has been calibrated
- [x] Angle FeedForward has been calibrated (SysID)
- [x] Spin PID has been calibrated
- [x] Spin FeedForward has benn calibrated (SysID)
## Motor configs
- [x] Angle motor gets correct constants in configurator
- [x] Spin motor gets correct constants in configurator
## Logger Inputs
- [x] AngleSetpoint is updating + logical value
- [x] CurrentAngle is updating + logical value
- [x] RollerSpeedSetpoint is updating + logical value
- [x] CurrentRollerSpeed is updating + logical value
- [x] CenterRollerSpeedSetpoint is updating + logical value
- [x] AngleMotorVoltage is updating + logical value
- [x] SpinMotorVoltage is updating + logical value
- [x] CenterMotorVoltage is updating + logical value
## Constants
- [x] Up angle has been calibrated
- [x] Down angle has been calibrated
## Subsystem functions
- [x] SetAngle sets the motor to the correct angle
- [x] SetRollerSpeed sets the roller to the correct speed
- [x] SetCenterRollerSpeed sets the center roller to the correct speed
## Subsystem command
- [x] SetAngle (Angle measure) command works as expected
- [x] SetAngle (Intake pose) command works as expected
- [x] SetRollerSpeed command works as expected
- [x] SetCenterRollerSpeed command works as expected
- [x] Intake command works as expected
- [x] stop command works as expected
