### ISSUE TITLE
Conveyor checklist

### ISSUE THREAD

**Issue by rakrakon** [Galaxia5987/robot-2024#41]
# Conveyor checklist
## Calibration
- [x] PID has been calibrated
- [x] Feedforward has been calibrated (SysID)
## Motor configs
- [x] Motor gets correct constants in configurator 
## Logger Inputs
- [x] VelocitySetpoint is updating & logical value
- [x] CurrentVelocity is updating & logical value
- [x] AppliedVoltage is updating & logical value
- [x] AppliedCurrent is updating & logical value
## Constants
- [x] Feed velocity has been calibrated
- [x] Setpoint tolerance has been calibrated
## Subsystem functions
- [x] SetVelocity sets the motor to the correct velocity
- [x] ReadyToFeed is updating & logical value
## Subsystem commands
- [x] SetVelocity command works as expected
