### ISSUE TITLE
Gripper checklist

### ISSUE THREAD

**Issue by rakrakon** [Galaxia5987/robot-2024#43]
# Gripper checklist
## Calibration
- [ ] PID has been calibrated
- [ ] Feedforward has been calibrated (SysID)
## Motor configs
- [ ] Motor gets correct constants in configurator 
## Logger Inputs
- [ ] AngleSetpoint is updating & logical value
- [ ] CurrentAngle is updating & logical value
- [ ] AngleMotorVoltage is updating & logical value
- [ ] encoderPosition is updating & logical value
- [ ] RollerPowerSetpoint is updating & logical value
- [ ] RollerMotorVoltage is updating & logical value
- [ ] hasNote is updating & logical value
- [ ] ### Acceleration is updating & logical value (currently not in use) 
## Subsystem function
- [ ] SetRollerMotorPower sets the motor to the correct power
- [ ] SetAngleMotorPower sets the motor to the correct power
- [ ] SetAngle sets the motor to the correct 
- [ ] HasNote upda
- [ ] AtSetpoint works as expected
## Subsystem commands
- [ ] SetAngle command works as expected
- [ ] SetPower command works as expected
- [ ] UpdateInternalEncoder command works as expected
## Constants
