### ISSUE TITLE
Gripper checklist

### ISSUE THREAD

**Issue by rakrakon** [Galaxia5987/robot-2024#44]
# Gripper checklist
## Calibration
- [x] PID has been calibrated
- [x] Feedforward has been calibrated (SysID)
## Motor configs
- [x] Motor gets correct constants in configurator 
## Logger Inputs
- [x] AngleSetpoint is updating & logical value
- [x] CurrentAngle is updating & logical value
- [x] AngleMotorVoltage is updating & logical value
- [x] encoderPosition is updating & logical value
- [x] RollerPowerSetpoint is updating & logical value
- [x] RollerMotorVoltage is updating & logical value
- [x] hasNote is updating & logical value
- [ ] Acceleration is updating & logical value (currently not in use) 
## Constants
- [x] Intake angle has been calibrated
- [x] Outtake angle has been calibrated
- [x] Intake power has been calibrated
- [x] Outtake power has been calibrated
- [x] Amp power normal has been calibrated
- [x] Amp power reverse has been calibrated
- [ ] Trap power has been calibrated
- [ ] Tolerance has been calibrated
- [ ] Gripper outtake min height has been calibrated
- [x] Angle inversion has been calibrated
- [x] Roller inversion has been calibrated
- [x] Absolute encoder 
## Subsystem function
- [x] SetRollerMotorPower sets the motor to the correct power
- [x] SetAngleMotorPower sets the motor to the correct power
- [x] SetAngle sets the motor to the correct 
- [x] HasNote updates & logical value
- [x] AtSetpoint works as expected
## Subsystem commands
- [x] SetRollerPower command works as expected
- [x] SetWristPosition command works as expected
- [x] Intake command works as expected
- [x] Outtake command works as expected
