### ISSUE TITLE
Elevator checklist

### ISSUE THREAD

**Issue by rakrakon** [Galaxia5987/robot-2024#45]
# Elevator checklist
## Calibration
- [ ] Feedforward has been calibrated (SysID)
- [ ] PID has been calibrated
- [ ] kG has been calibrated
## Motor configs
- [ ] Motor gets correct constants in configurator 
## Logger Inputs
- [ ] HooksHeight is updating & logical value
- [ ] CarriageHeight is updating & logical value
- [ ] HeightSetpoint is updating & logical value
- [ ] ControlMode is updating
- [ ] isBottom is updating & logical value
- [ ] isTop is updating & logical value
- [ ] StopperAngle is updating & logical value
- [ ] StopperSetpoint is updating & logical value
## Constants 
- [ ] Open position has been calibrated
- [ ] Locked position has been calibrated
- [ ] Height tolerance has been calibrated
- [ ] Stopper tolerance has been calibrated
- [ ] Hooks mass has been calibrated
- [ ] Elevator mass has been calibrated
- [ ] Gripper to hooks has been calibrated
## Subsystem function
- [ ] SetPower sets the motor to the correct power
- [ ] SetHeight sets the motor to the correct height
- [ ] OpenStoppper opens the stopper
- [ ] CloseStopper closes the stopper
- [ ] StopMotor stops the motor
- [ ] atHeightSetpoint is updating & logical value
- [ ] stopperAtSetpoint is updating & logical value
## Subsystem commands
- [ ] SetHeight command works as expected

**Comment by katzuv** [comment]
Should also check that the auxiliary motor follows correctly.
About "UpdateInternalEncoder command works as expected", it should be handled by the Talon FX itself (I don't recall having a command for that in the elevator), so just make sure it works.
Also, the elevator does not have a `hasNote` getter. Looks like some copy&paste was done in the issues. You should check all of the issues and make sure they are up to date.

**Comment by rakrakon** [comment]
This checklist was not finished
