### ISSUE TITLE
Command groups checklist

### ISSUE THREAD

**Issue by rakrakon** [Galaxia5987/robot-2024#47]
# Command groups checklist
## Commands
- [ ] RetractGrillevator works as expected
- [x] Feed works as expected
- [x] Intake works as expected
- [ ] ScoreTrap works as expected
- [ ] OuttakeGripper works as expected
- [ ] OuttakeShooter works as expected 
## Constants
- [ ] Elevator min height has been calibrated
- [ ] Elevator max height has been calibrated
- [ ] Start climb height has been calibrated
- [ ] End climb height has been calibrated
- [ ] Elevator outtake height has been calibrated
- [ ] Wrist base angle has been calibrated
- [ ] Wrist angle amp forward has been calibrated
- [ ] Wrist min backwards angle has been calibrated
- [ ] Wrist trap angle has been calibrated
