### ISSUE TITLE
Score state checklist

### ISSUE THREAD

**Issue by rakrakon** [Galaxia5987/robot-2024#49]
# Score state checklist
## interface default commands
- [ ] IsRed is working as expected
## Functions
- [ ] CreateBoundsMap works as expected
## Constants
- [ ] Optimal points shoot blue has been calibrated
- [ ] Optimal points climb blue has been calibrated
- [ ] Optimal points amp blue & red has been calibrated
- [ ] Speaker pose blue has been calibrated
- [ ] Min distance to turn gripper has been calibrated
- [ ] Turn tolerance has been calibrated
- [ ] Speaker target height has been calibrated
