### ISSUE TITLE
Shoot state checklist

### ISSUE THREAD

**Issue by rakrakon** [Galaxia5987/robot-2024#50]
# Shoot state checklist
## Functions
- [ ] Update in bounds works as expected
## Commands
- [ ] Rotate command works as expected
- [ ] Calculate target commands works as expected
- [ ] Prepare subsystems command works as expected
- [ ] DTOP works as expected
- [ ] Score works as expected
