### ISSUE TITLE
Amp state checklist

### ISSUE THREAD

**Issue by rakrakon** [Galaxia5987/robot-2024#51]
# Amp state checklist
## Commands
- [ ] Calculate targets works as expected
- [ ] Prepare subsystems works as expected
- [ ] DTOP works as expected
- [ ] Score works as expected
