### ISSUE TITLE
Climb state checklist

### ISSUE THREAD

**Issue by rakrakon** [Galaxia5987/robot-2024#52]
# Climb state checklist
## Commands
- [ ] Prepare subsystems command works as expected
- [ ] DTOP works as expected
- [ ] Score works as expected
